input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [app] {
    mutate { add_field => { "service" => "%{app}" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "clouddisk-logs-%{+YYYY.MM.dd}"
  }
}
